#cloud-config

write_files:
  - path: /etc/systemd/timesyncd.conf
    content: |
      [Time]
      NTP=169.254.169.123
  - encoding: b64
    path: /etc/cloudwatch-agent-config.json
    owner: root:root
    permissions: '0644'
    content: ${cwa_content}
coreos:
 update:
  reboot-strategy: off
 units:
   - name: update-engine.service
     command: stop
   - name: locksmithd.service
     command: stop
   - name: settimezone.service
     command: start
     content: |
       [Unit]
       Description=Set Timezone
       [Service]
       ExecStart=/usr/bin/timedatectl set-timezone Asia/Tokyo
       RemainAfterExit=yes
       Type=oneshot
   - name: systemd-timesyncd.service
     command: restart
   - name: amazon-cloudwatch-agent.service
     command: start
     enable: true
     content: |
       [Unit]
       Description=Amazon CloudWatch Agent
       After=docker.service
       Requires=docker.service
       [Service]
       Restart=on-failure
       RestartSec=30
       RestartPreventExitStatus=5
       SyslogIdentifier=amazon-cloudwatch-agent
       ExecStartPre=-/usr/bin/docker kill amazon-cloudwatch-agent
       ExecStartPre=-/usr/bin/docker rm amazon-cloudwatch-agent
       ExecStartPre=/usr/bin/docker pull amazon/cloudwatch-agent
       ExecStart=/usr/bin/docker run --name amazon-cloudwatch-agent \
                                     --privileged \
                                     --net host \
                                     --pid host \
                                     --volume=/etc/cloudwatch-agent-config.json:/etc/cwagentconfig \
                                     amazon/cloudwatch-agent
       ExecStop=/usr/bin/docker stop amazon-cloudwatch-agent
       [Install]
       WantedBy=multi-user.target
