version: "3"
services:
  nginx:
    image: ${IMG_URI}/alb-ecs-fargate-nginx
    build:
      context: ./nginx
    command: >
      /bin/sh -c
      "envsubst '
      $$UPSTREAM_SERVER
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    environment:
      UPSTREAM_SERVER: unix:/app/tmp/express.sock
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-group: /alb-ecs-fargate/staging
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: nginx
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - app
    volumes:
      - "app-data:/app:ro"
  app:
    image: ${IMG_URI}/alb-ecs-fargate-node
    build:
      context: ./app
    environment:
      - SOCKET_PATH=/app/tmp/express.sock
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-group: /alb-ecs-fargate/staging
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: nginx
    networks:
      - default
    volumes:
      - "app-data:/app:rw"
networks:
  default:
volumes:
  app-data:
