version: "3"
services:
  nginx:
    image: 752096157676.dkr.ecr.ap-northeast-1.amazonaws.com/alb-ecs-ec2
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    environment:
      ENV: staging
      TZ: Asia/Tokyo
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-group: /alb-ecs-fargate/staging
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: nginx
    ports:
      - "80:80"
