version: "3"
services:
  nginx:
    image: ${IMG_URI}/alb-ecs-fargate-nginx
    build:
      context: ./nginx
    environment:
      ENV: staging
      TZ: Asia/Tokyo
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-group: /alb-ecs-fargate/staging
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: nginx
    ports:
      - "80:80"
