#cloud-config

repo_update: true
repo_upgrade: security
runcmd:
  - curl -O https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
  - dpkg -i amazon-ssm-agent.deb
