#cloud-config

repo_update: true
repo_upgrade: security
write_files:
  - path: /etc/sysctl.d/99-sysctl.conf
    owner: root
    permissions: 0644
    content: |
      fs.file-max=1048576
      fs.nr_open=1048576
      net.core.somaxconn=65535
      net.ipv4.tcp_max_syn_backlog=65536
      net.core.netdev_max_backlog=16384
      net.core.rmem_max=16777216
      net.core.wmem_max=16777216
      net.ipv4.tcp_rmem=4096 87380 16777216
      net.ipv4.tcp_wmem=4096 65536 16777216
      net.ipv4.tcp_max_tw_buckets=65536
      net.ipv4.conf.all.arp_ignore =1
      net.ipv4.conf.all.arp_announce=2
      net.ipv4.ip_local_port_range=1024 65535
      net.ipv4.tcp_fin_timeout=15
      net.ipv4.tcp_tw_reuse=1
      vm.swappiness=10
      vm.panic_on_oom=1
  - path: /etc/systemd/system.conf.d/limits.conf
    owner: root
    permissions: 0644
    content: |
      [Manager]
      DefaultLimitNOFILE=65536
      DefaultLimitNPROC=65536
  - path: /etc/sysconfig/docker
    owner: root
    permissions: 0644
    content: |
      DAEMON_MAXFILES=1048576
      OPTIONS="--default-ulimit nofile=65536:65536"
      DAEMON_PIDFILE_TIMEOUT=10
  - path: /etc/ecs/ecs.config
    content: |
      ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","syslog","fluentd","awslogs"]
      ECS_CLUSTER=${ecs_cluster}
      ECS_DATADIR=/data
      ECS_ENABLE_SPOT_INSTANCE_DRAINING=true
      ECS_LOGFILE=/log/ecs-agent.log
      ECS_LOGLEVEL=info
  - path: /etc/cloudwatch-agent-config.json
    encoding: b64
    owner: root
    permissions: 0644
    content: ${cwa_content}
runcmd:
  - systemctl restart systemd-sysctl
  - systemctl restart docker.service
  - systemctl stop postfix.service
  - systemctl disable postfix.service
