AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Parameters:
  Namespace:
    Type: String
  Stage:
    Type: String
    Default: stg
  # VpcId:
  #   Type: AWS::EC2::VPC::Id
  # VpcSecurityGroupId:
  #   Type: AWS::EC2::SecurityGroup::Id
  # VpcSubnetIds:
  #   Type: List<AWS::EC2::Subnet::Id>

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      # VpcConfig:
      #   SecurityGroupIds:
      #     - !Ref VpcSecurityGroupId
      #   SubnetIds: !Ref VpcSubnetIds
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: get
          Tags:
            Namespace:
              Ref: Namespace
            Stage:
              Ref: Stage
      Tags:
        Namespace:
          Ref: Namespace
        Stage:
          Ref: Stage

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/hello"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
