AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3
  Api:
    OpenApiVersion: 3.0.2

Parameters:
  Namespace:
    Type: String
  Stage:
    Type: String
    Default: stg
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  VpcSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: example-apigw-rest
      EndpointConfiguration: REGIONAL
      StageName: prod
      TracingEnabled: true
      Auth:
        ResourcePolicy:
          CustomStatements: {
            Effect: 'Allow',
            Action: 'execute-api:Invoke',
            Resource: ['execute-api:/*/*/*'],
            Principal: '*'
          }
      MethodSettings:
      - HttpMethod: '*'
        ResourcePath: /*
        DataTraceEnabled: true
        LoggingLevel: ERROR
        MetricsEnabled: true
        ThrottlingBurstLimit: 10
        ThrottlingRateLimit: 20
      Tags:
        Namespace:
          Ref: Namespace
        Stage:
          Ref: Stage
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: example-apigw-rest
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      VpcConfig:
        SecurityGroupIds:
          - !Ref VpcSecurityGroupId
        SubnetIds: !Ref VpcSubnetIds

      AutoPublishAlias: live
      DeploymentPreference:
        Enabled: true
        Type: Linear10PercentEvery10Minutes
      Tags:
        Namespace:
          Ref: Namespace
        Stage:
          Ref: Stage
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref ApiGatewayApi

Outputs:
  ApiGatewayApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
