version: "3"
services:
  nginx:
    environment:
      ENV: staging
      TZ: Asia/Tokyo
    image: ${IMG_URI}:${IMG_TAG}
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-group: /example/ecs-ec2/stg
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: nginx
    ports:
      - "80:80"
