version: "3.7"
services:
  app:
    image: 752096157676.dkr.ecr.ap-northeast-1.amazonaws.com/ecs-ec2
    build:
      context: .
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default
networks:
  default:
