#cloud-config

repo_update: true
repo_upgrade: security
write_files:
  - path: /etc/yum.repos.d/mongodb-org-4.2.repo
    owner: root
    permissions: 0644
    content: |
      [mongodb-org-4.2]
      name=MongoDB Repository
      baseurl=https://repo.mongodb.org/yum/redhat/7/mongodb-org/4.2/x86_64/
      gpgcheck=1
      enabled=1
      gpgkey=https://www.mongodb.org/static/pgp/server-4.2.asc
  - path: /etc/yum.repos.d/pritunl.repo
    owner: root
    permissions: 0644
    content: |
      [pritunl]
      name=Pritunl Repository
      baseurl=https://repo.pritunl.com/stable/yum/oraclelinux/7/
      gpgcheck=1
      enabled=1
runcmd:
  - yum -y install oracle-epel-release-el7
  - yum-config-manager --enable ol7_developer_epel
  - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A
  - gpg --armor --export 7568D9BB55FF9E5287D586017AE645C0CF8E292A > key.tmp; sudo rpm --import key.tmp; rm -f key.tmp
  - yum -y remove iptables-services
  - yum -y install pritunl mongodb-org
  - systemctl enable mongod pritunl
  - systemctl start mongod pritunl
  - sleep 60
  - pritunl setup-key

