#cloud-config
repo_update: true
repo_upgrade: none
write_files:
  - encoding: b64
    path: /etc/cloudwatch-agent-config.json
    owner: root:root
    permissions: '0644'
    content: ${cwa_content}
runcmd:
  - |
    . /etc/os-release
    case $NAME in
      "Amazon Linux") echo "Installing for Amazon Linux."
        yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
        yum install -y https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
        ;;
      Centos) echo "Installing for Centos."
        yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
        yum install -y https://s3.amazonaws.com/amazoncloudwatch-agent/centos/amd64/latest/amazon-cloudwatch-agent.rpm
        ;;
      Debian) echo "Installing for Debian."
        curl -O https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
        dpkg -i amazon-ssm-agent.deb
        curl -O https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb
        dpkg -i -E ./amazon-cloudwatch-agent.deb
        ;;
      Ubuntu) echo "Installing for Ubuntu."
        curl -O https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
        dpkg -i amazon-ssm-agent.deb
        curl -O https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd63/latest/amazon-cloudwatch-agent.deb
        dpkg -i -E ./amazon-cloudwatch-agent.deb
        ;;
      *)
        echo "Not supported"
    esac
  - /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/etc/cloudwatch-agent-config.json -s
