on:
  push:
    branches:
    - master
name: validate
jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        examples:
          - alb-asg-lc
          - backend
          - ssm-cloudwatch-agent-config
          - vpc-nati
    steps:
    - uses: actions/checkout@v1
    - name: Install tfenv
      run: |
        git clone https://github.com/tfutils/tfenv.git ~/.tfenv
        echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bash_profile
        source ~/.bash_profile
        cd ./examples && tfenv install && terraform --version
    - name: Terraform validate
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        source ~/.bash_profile
        cd ./examples/${{matrix.examples}} && terraform --version && terraform init && terraform validate

