on:
  push:
    branches:
    - master
name: validate
jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        examples:
          - account
          - alb-asg-lc
          - alb-ecs-ec2/common
          - alb-ecs-ec2/staging
          - alb-ecs-fargate/common
          - alb-ecs-fargate/staging
          - asg-lc
          - asg-lt
          - backend
          - cloudfront-s3
          - cloudwatch-log-groups
          - cognito4iam
          - ec2-instance-connect
          - ecr-repos
          - ecr-repos
          - es-global
          - es-vpc
          - glue-athena
          - iam-management
          - rds-aurora-mysql-snapshot
          - security
          - sns-budgets
          - sns-event
          - ssm-cloudwatch-agent-config
          - vpc-natgw
          - vpc-nati
          - vpn-pritunl
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install tfenv
      run: |
        git clone https://github.com/tfutils/tfenv.git ~/.tfenv
        echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bash_profile
        source ~/.bash_profile
        cd ./examples && tfenv install && terraform --version
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
        role-duration-seconds: 1200
    - name: Terraform validate
      run: |
        source ~/.bash_profile
        cd ./examples/${{matrix.examples}} && terraform --version && terraform init && terraform validate

